### ISSUE TITLE
Add Save/Load Feature

### ISSUE THREAD

**Issue by hooh-hooah** [ore-/AI_Graphics#1]
I'm working on it

It saves variable in .xml format - (preset)
Planning to add scene saving too

**Comment by ore-** [comment]
Thanks @hooh-hooah . My plan is to support external LUTs as no manual preset would beat a good LUT and there are plenty free and good ones.

**Comment by ore-** [comment]
@hooh-hooah we don't really need the preset to be manually editable right? since we need to support embedding the data in scene, let's just serialize the data with messagepack so we can just use the same code for both preset and embedding in scene. if we really want it to be manually editable, can we use json please?

**Comment by hooh-hooah** [comment]
I'm trying to achieve following features
1. Save/Load Default Preset
2. Save/Load Preset to Folder
3. Embed Preset data to scene.

Since not all people actually edit preset by hands with notepad, I was planning to use MessagePack Bytes Format to save preset data. It's easy, fast to develop and implement and extend.
Also, We're going to save much more time to implement saving feature by using that one.

I'm currently aiming to save primitive data like string and float - 
About that external LUT (or other post processing textures)... We're going to need more time to think about that.

**Comment by ore-** [comment]
on messagepack, great, sounds like we are on the same page.

**Comment by hooh-hooah** [comment]
To make classes messagepack compatible, we need to make the messagepack annotated classes and class variables public.
I'm changing it right now but just in case, may i ask why did you set Settings classes internal? If it's basic reason i'm about to make it change permanent

**Comment by ore-** [comment]
I usually only make things public when there’s a need to. If messagepack requires that the class be public, lets make a public struct that encapsulates the private attributes and serialise only that and nothing else. We need to save as little as possible to avoid binary incompatibility. I haven’t used messagepack before but just thinking out loud. the preset and scene embedded data needs to be backward/forward compatible if possible. As long as we try to do that, go ahead with your change. Thanks

**Comment by hooh-hooah** [comment]
Thanks for clarifying.
since I've got Save/Load and Scene Embedding working, It's time to make it look cleaner and minimize.
It's currently live on my fork's [Link](branchhttps://github.com/hooh-hooah/AI_Graphics/tree/feature/preset)
Currently it's messy because I just wanted to see if it works or not. I'm going to do some cleanup/capsule process so if you want me to follow some guideline you can link me to that guideline too.

**Comment by ore-** [comment]
@hooh-hooah I invited you as a collaborator on the repo, please accept. Unless you want to release and maintain AIGraphics as a fork, I would prefer you work directly on this repo. I respect you as a collaborator and contributor so feel free to make yourself at home. I don't have any hard and fast guideline but as long as we agree on a sdlc that works for both of us, all I ask is that we just do some informal review of each other's code and keep ourselves in check.

**Comment by hooh-hooah** [comment]
Thanks for invitation, I'll accept that and make another branch after save/load.
Since I'm more familiar with scripts and functional programming... Sometimes my codes will kinda look odd for Objective Oriented Programming :/ just letting you know.

**Comment by ore-** [comment]
likewise. I'm not a native c# programmer so please bear with me as well . let's learn from each other. on that topic, please review my change for lens dirt. I forgot to make a pull request instead of directly committing, we should do that going forward so we can leverage the team/code review tooling.

**Comment by hooh-hooah** [comment]
It seems it needs some resources to test it out.
can you upload the packages on any uploader?

**Comment by ore-** [comment]
here you go: https://mega.nz/#F!7N8VHZ5D!3aBnDJJSA5OE1d64sK5vLA

**Comment by hooh-hooah** [comment]
@ore- 
Okay, I've got Post Processing Saving working - But there is few things needs to be sorted before making it live. 

1. Currently It's saving ALL values. I think few values should be not saved on "preset". values such as Window Size and Font Size or Few Global Settings. 
What values should we keep out from the preset file?
These are my pick for now:
- Font Size
- Window Width
- Window Height
- Show Advanced Settings

2. How should we approach to Saving/Loading Preset to remote location? I'm currently thinking about opening file explorer window to load or save presets.
What's your thoughts?

3. I'm currently making "Parameters" classes ([Example](https://github.com/hooh-hooah/AI_Graphics/blob/feature/preset/AI_Graphics/AI_Graphics/SettingParams/PostProcessing.cs)) that stores values to be packed with MessagePacker to minimize exposing variables. I'm going to finalize the project tomorrow, If you're against it, please leave opinion.

**Comment by ore-** [comment]
For 1, I'm ok with using native window file/directory dialog if it makes things easier.
For 2, I looked at your example, may be I'm mistaken but it's more complicated than I think it needs to be. I read the [Object-Serialization](https://github.com/neuecc/MessagePack-CSharp#object-serialization) documentation, all public members would be serialized. I designed for the Settings classes to represent the settings for each function and meant for them to be serializable. So no need to make separate Parameter classes. e.g.:

```c#
namespace AIGraphics.Settings
{
    [MessagePackObject(keyAsPropertyName: true)]
    public class JustAnotherSetsOfSettings
    {
        private int _aPrivateVar;
        private float _anotherPrivateVar;

        public int aVar {get;set;}
        public float AnotherVar
        {
             get => _anotherPrivateVar;
             set
             {
                 //do a much of stuff 
                 _anotherPrivateVar = value;
             }
        }             
    }
}
```
if we do:
```c#
MessagePackSerializer.SerializeToJson(new JustAnotherSetsOfSettings { aVar = 10; AnotherVar = 11} ); 
```
wouldn't it store the below?
```c#
//{"aVar"=10, "AnotherVar"=11} 
```
And when we restart, isn't it all we need to do is to deserialize and instantiate each of the Settings classes in AIGrapahic's Start() with the deserialized instance?

**Comment by ore-** [comment]
@hooh-hooah another thought on 1. perhaps even simpler is to provide a single line textbox for specifying a preset name next to a save button. then one can choose from a list of presets to load with a selector gui that behaves like the reflection probe selections. The height of the selectors would be bound by a vertical slider to prevent the window from growing too tall. how does that sound?

**Comment by hooh-hooah** [comment]
1. About Serialization
Well, yeah.. That was I initially thought about but I tried some another approach. But I think I was overthinking about that. I'm going to change it like that.
2. Preset Save/Load UI
Maybe like this? this also works. 
![image](https://user-images.githubusercontent.com/55322444/78305193-478be880-757b-11ea-97a6-9eb9b7df246b.png)

**Comment by ore-** [comment]
What does save/load do compare with save defaults/load defaults? I assume this is without native file dialog, where do users type in name of presets?

**Comment by ore-** [comment]
From a screen estate perspective, I think we should have multiple columns as the preset usually has a short name and we should limit it to fit. Having one column would be a bit of waste of space. Have a look at Util.Selection() and where it’s being used at the moment. Just wrap a slider around it.
