### ISSUE TITLE
Chinese text sharing authorization request for personal translation

### ISSUE THREAD

**Issue by doom222908** [ore-/AI_Graphics#100]
Hello! Your plug-in has no Chinese. I translated it into Chinese using the Korean text of the plug-in. Can I share Chinese text in zodgame forum? The text is machine translated, not necessarily accurate. I hope to get your authorization.

**Comment by hooh-hooah** [comment]
If you have proper Chinese translation, I can include that txt file as default text file. 
Feel free to send/pull request new files. :)

**Comment by doom222908** [comment]
For the accuracy of the text, I'd like to share it first, ask for other netizens' modification opinions, and then send it to you.

**Comment by hooh-hooah** [comment]
> For the accuracy of the text, I'd like to share it first, ask for other netizens' modification opinions, and then send it to you.

@doom222908 You can take your time to boost the quality of translation. We can add translation in any time.

**Comment by ore-** [comment]
closing this - superseded by #107
