### ISSUE TITLE
Cannot enable hard shadows.

### ISSUE THREAD

**Issue by Renatus-AI** [ore-/AI_Graphics#101]
I'm on AIG Ver 0.3.1

I can't enable hard shadows on any of my light sources, directional, point, nor spot.

When you click on hard it will just move to none. So the only options you get are either soft shadows or no shadows.

**Comment by hooh-hooah** [comment]
@Renatus-AI I need more detailed information.
Give me 100% way to replicate the issue and some preset/scene that i can test.

**Comment by hooh-hooah** [comment]
Fixed in 61d0245424a13a40f1fe923a3d46274d01d914d3
Will be merged in next release.
