### ISSUE TITLE
Light guidelines dissapear

### ISSUE THREAD

**Issue by DreadNinja** [ore-/AI_Graphics#104]
Adding a point light or a spotlight will appear without light guidelines

## Expected Behavior
Show the light guidelines

## Current Behavior
Light guidelines dissapear when added

## Used AI_Graphics Version
AIGraphics v0.3.1

## Steps to Reproduce

Set up a light, open aig, you'll se your light doesnt appear then click the + icon, on and off your light
You can "fix it" by object copy, but sometimes just gets crazy and you have to restart the studio

![AI_2020-05-16-13-46-05-669](https://user-images.githubusercontent.com/65449737/82119931-a485db80-9782-11ea-9b35-84df18abd40d.png)

![AI_2020-05-16-14-52-15-546](https://user-images.githubusercontent.com/65449737/82120231-ee6fc100-9784-11ea-969e-ff50d3f362b0.png)

![AI_2020-05-16-14-57-59-707](https://user-images.githubusercontent.com/65449737/82120356-ad2be100-9785-11ea-8c60-f86a57588af0.png)

![guidelines](https://user-images.githubusercontent.com/65449737/82121288-19114800-978c-11ea-851a-5008cc14778e.png)

I've noticed that adding a new light will just make guidelines dissapear even without openning ai ui, quick fix is copying the objetc

**Comment by hooh-hooah** [comment]
Well shit

**Comment by ore-** [comment]
There's no issues here. AIGraphics uses [alloy area lights](https://alloy.rustltd.com/docs/docs_files/sites/alloy/files/html_export/export1510649347/node/185/index.html) by default. Adjust Specular Highlight (and length for point lights) to see the guide lines.

**Comment by ore-** [comment]
Also, I cannot reproduce "Set up a light, open aig, you'll se your light doesnt appear". I see AIGraphics correctly enumerated the light as I add them through the studio menu.

**Comment by DreadNinja** [comment]
What Im trying to report is that these white lines dissapear using aig
![82121288-19114800-978c-11ea-851a-5008cc14778e](https://user-images.githubusercontent.com/65449737/82891761-96884580-9f4e-11ea-80be-523b85872e5b.png)

**Comment by ore-** [comment]
@DreadNinja did you see my comment above how to adjust the intensity of the guide lines using alloy's specular highlight?

**Comment by DreadNinja** [comment]
Yes, I read the whole documentation but its not that, these are added lights in studio through add > light. That when you use AIG you cant see where they are facing, the size etc even tho they still work. Sorry If you missunderstood something Im trying to explain myself as best I can
