### ISSUE TITLE
Translation document of Chinese text

### ISSUE THREAD

**Issue by doom222908** [ore-/AI_Graphics#107]
Hello! I have finished translating the Chinese text! I also compared the Chinese translation of Japanese text made by other netizens, which should be more accurate. Now I will send it to you! I would like to have Chinese options in the next version.

https://mega.nz/file/0VRThADB#qSndZLTnrTT6KQ6zYcIYPcL16W21nqtSVN0f35Ugo_w

**Comment by ore-** [comment]
incorporated, will be available in the next release.
