### ISSUE TITLE
Dark background color creating undesired contrast

### ISSUE THREAD

**Issue by NolanH96** [ore-/AI_Graphics#111]
I'm getting a lot of glare from certain angles with the settings I have enabled, and I believe it has something to do with the the backlighting. Whenever enough of a dark color is occupying the screen, the characters and objects on screen behave as if the contrast has been turned up to maximum. This only seems to occur at a certain luminosity.
Demonstration here: https://i.gyazo.com/a142c270c8af203302645ae35ae06c7c.mp4
Even with the high contrast, it can be minimized slightly by zooming in on the subject.

Preset I use when this occurs:
[Character Creator2.zip](https://github.com/ore-/AI_Graphics/files/4685083/Character.Creator2.zip)

## Used AI_Graphics Version
 v0.3.1

**Comment by ore-** [comment]
@NolanH96 is auto exposure turned on?

**Comment by NolanH96** [comment]
Yes, that was the issue apparently. This thread can be deleted.
