### ISSUE TITLE
Support Amplify Occlusion

### ISSUE THREAD

**Issue by hooh-hooah** [ore-/AI_Graphics#2]
It's there but somehow ILLUSION is not utilizing it.

![image](https://user-images.githubusercontent.com/55322444/77901867-46c52f00-72bb-11ea-84ef-2ecc7e382177.png)

**Comment by ore-** [comment]
Yep, noticed quite a few underutilized plugins.

**Comment by hooh-hooah** [comment]
I'm thinking of for "Generated Skybox"
We can use two modes:
1. Default Unity Generated Skybox
2. Enviro Skybox 
Enviro Skybox is already implemented by default - only thing we're going to need is figure out where is the skybox shader is and what paramater to manipulate to simulate "Time of Day"

**Comment by ore-** [comment]
Is the generated skybox more for in-game use? can you give elaborate a bit more on the generated skybox, not sure I follow the use case.

**Comment by hooh-hooah** [comment]
it's focusing on generating skybox.
Just like how Joan's IBL did, set sun light source, set skybox thickness, etc.
so we can get more choice on skybox cubemap with small size of disk space.

**Comment by ore-** [comment]
I've not looked at Joan's IBL before, will check.

**Comment by ore-** [comment]
We should either rename this issue or make a separate issue for this skybox topic. Also Amplify just made their occlusion, colour and motion package open source, we should replace the unity post stack with the amplify ones. Let's make an issue for each if you agree on using those packages.
