### ISSUE TITLE
Default Reflection Probe is too small

### ISSUE THREAD

**Issue by hooh-hooah** [ore-/AI_Graphics#20]
Maybe we should make it bigger and make project as cube default?
Also thinking about lowering it's priority because a map with some reflection probe probably set up with nice manner so I rather prioritize maps' reflection probe rather than generated probe.

**Comment by ore-** [comment]
You must've already seen this in OnSceneLoad:
```            
parent?.SkyboxManager?.SetupDefaultReflectionProbe();
````
The above turns off the DefaultReflectionProbe if there is any other real time reflection probes. Happy to change it to turn off if there's ANY reflection probes regardless of types in the scene.
