### ISSUE TITLE
Save and restore settings for each light in a scene

### ISSUE THREAD

**Issue by ore-** [ore-/AI_Graphics#22]

**Comment by hooh-hooah** [comment]
I guess this is gonna be mid-term goal..

**Comment by ore-** [comment]
I want to give it a stab to see how difficult it is first. let's aim to release a version with save/load functionality this Friday/Saturday, ok? I think being able to restore light setting is crucial because you can do so with builtin normal scene, would be very strange if we ask the user to adjust the lighting in the base game and do everything else in AIGraphics because we can't save light.
