### ISSUE TITLE
Add Lens Dirt Support on Bloom

### ISSUE THREAD

**Issue by hooh-hooah** [ore-/AI_Graphics#3]
it makes bloom more dramatic.

**Comment by ore-** [comment]
@hooh-hooah I can take this one if you want as there are 3 more post stack effects I haven't got round to yet but soon.

**Comment by ore-** [comment]
@hooh-hooah what do you think about this lens dirt effect? it's pretty popular. briefly testing it under unity looks pretty good. https://github.com/sonicether/SE-Natural-Bloom-Dirty-Lens

**Comment by ore-** [comment]
@hooh-hooah can you review and comment on the changes for lens-dirt please? Ideally we don’t cache all the pngs to save memory but I didn’t do that.
