### ISSUE TITLE
Post Processing is still kinda weird in Character Creation.

### ISSUE THREAD

**Issue by hooh-hooah** [ore-/AI_Graphics#34]
It does loads correctly
but i think character creation scene actually using more than 2 post processing before clicking post processing tab.

**Comment by ore-** [comment]
to debug, click the Show Advanced Settings toggle, and you will see all (2) the pp volumes used. Studio also has 2 but the other one has 0 weight by default. Maker has both with weight == 1 by default

**Comment by hooh-hooah** [comment]
oooh I get it

**Comment by hooh-hooah** [comment]
ooh apparently 2d volume is just for 2d confirm ui...

**Comment by ore-** [comment]
we could do. I would like to avoid overriding any default settings, and allow for any changes to happen through menus we expose. we could provide a sane and more appropriate default preset but no settings should be overridden in code. I think the saving code should be generic enough to all available pp volumes. if this is just too much work, we can make it a medium term goal but my fear is that it may change the save settings a lot and make previous scene data incompatible.

**Comment by hooh-hooah** [comment]
> we could do. I would like to avoid overriding any default settings, and allow for any changes to happen through menus we expose. 
Me too but there is no reason to keep more than 2 post processing volumes. This plugin is designed for Maker and Studio atm.
I know there is still some people still prefers default ILLUSION look but...

> we could provide a sane and more appropriate default preset but no settings should be overridden in code. I think the saving code should be generic enough to all available pp volumes. if this is just too much work, we can make it a medium term goal 
As you said, we can keep Original Feeling as built-in preset. There is already few ideas for quick preset:
- Default ILLUSION Look
- Fast Mode (Turn off all PP, Scale down everything)
- Some Well Made Presets

> but my fear is that it may change the save settings a lot and make previous scene data incompatible.
Yes, that is my fear too but that's why we have #9.

**Comment by ore-** [comment]
sure, let's go with your 3 bullets.
