### ISSUE TITLE
The blue background light cant be eliminated

### ISSUE THREAD

**Issue by Kim1232123** [ore-/AI_Graphics#50]
![0989](https://user-images.githubusercontent.com/63515081/79051764-9ebd4780-7c64-11ea-8615-175b6ab8338e.PNG)

**Comment by hooh-hooah** [comment]
Now you can turn on and off the light.
Background blue light is disabled for default.
![image](https://user-images.githubusercontent.com/55322444/79117835-27ec8f80-7dc7-11ea-9f87-a10634851bd2.png)
