### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Chrixis** [ore-/AI_Graphics#52]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our slack channel. Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## Steps to Reproduce

-->

1.
2.
3.
4.

**Comment by Chrixis** [comment]
It says when is executed Ai that isnt compatible with dhhai4mod
![bug](https://user-images.githubusercontent.com/63095063/79061589-b7772e80-7c5f-11ea-803d-aa88c2785baf.png)

**Comment by ore-** [comment]
No bug. What the log says is exactly what it is, AIGraphics is not compatible with DHH. If you want to use AIGraphics, disable DHH and vice versa.
