### ISSUE TITLE
DoF Auto Focus/Focal Distance is not getting saved.

### ISSUE THREAD

**Issue by hooh-hooah** [ore-/AI_Graphics#57]
## Expected Behavior
Aufo Focus and Focal Distance must be saved.

## Current Behavior
Not Saved.

## Used AI_Graphics Version
0.2.0

## Steps to Reproduce
1. Save a profile with DoF
2. Load it
3. Disappoint

**Comment by cochese9000** [comment]
Not sure if it's related (or even deliberate?), but Field of View is also not saved.

**Comment by hooh-hooah** [comment]
> Not sure if it's related (or even deliberate?), but Field of View is also not saved.
It does get saved. You can make another issue with video so I can investigate it.
