### ISSUE TITLE
Chromatic Aberration and Grain have no effect in studio

### ISSUE THREAD

**Issue by ore-** [ore-/AI_Graphics#59]
## Expected Behavior
Take effect and they do in maker

## Current Behavior
No effect in studio, only maker

## Used AI_Graphics Version
0.2.0

## Steps to Reproduce
start studio and turn each effect on in studio

**Comment by hooh-hooah** [comment]
https://thumbs.gfycat.com/BonyUnfortunateHypacrosaurus-size_restricted.gif

**Comment by ore-** [comment]
Happy that it works for you, it doesn’t for me. Feel free to leave it with me but please don’t close.

**Comment by hooh-hooah** [comment]
You can embed scene if you want

**Comment by ore-** [comment]
Appreciate it but not sure how that would allow you to investigate, best case is you see the settings being saved but I still don’t them taking effect, worst case is you don’t see the effect being saved but I can check those on my end too

**Comment by hooh-hooah** [comment]
Well maybe it could related with plugin interference

**Comment by hooh-hooah** [comment]
Try to remove betterAA

**Comment by ore-** [comment]
I don't have betterAA

**Comment by hooh-hooah** [comment]
Update?

**Comment by ore-** [comment]
works on 0.3.1.
