### ISSUE TITLE
Change Bloom LensDirt Texture Parameter Save Friendly

### ISSUE THREAD

**Issue by hooh-hooah** [ore-/AI_Graphics#6]
I need path to texture to embed bloom info to the scene.
but current bloom LensDirt only stores Texture values. 🤔

**Comment by ore-** [comment]
got it. @hooh-hooah let's start using pull request so we can actually comment directly on each other's code, this is a much faster way of working together. Can you start creating pull request for your save/load changes? much easier for me to review and discuss. Thanks.
