### ISSUE TITLE
Inconsistent lighting

### ISSUE THREAD

**Issue by Chernobog95** [ore-/AI_Graphics#64]
When moving around camera, depending on angle the brightness of the light changes considerably, rapidly and for example if you were infront of character, rotate 45 degrees up/above or down/below character. Especially jarring with characters that have high color brightness value such as white as wall paint.

**Comment by ore-** [comment]
Sounds like you have Auto Exposure turned on, and the setting (I assume default as you seem unaware) is giving you unexpected behaviour. If so, please either turn off Auto Exposure or adjust its settings to how you want it. If you don't understand how to adjust the settings, please refer to unity's official manual for post processing v2 for an explanation.

Closing issue as this is not an issue with the plugin.
