### ISSUE TITLE
Objects have no reflections

### ISSUE THREAD

**Issue by MonkeyDocs** [ore-/AI_Graphics#75]
## Expected Behavior
Objects should be reflected on reflective surface

## Current Behavior
Objects aren't reflected on reflective surface, only skybox

## Used AI_Graphics Version
v0.2.0

## Steps to Reproduce
![2020](https://user-images.githubusercontent.com/61049870/80029109-dbb4f400-8518-11ea-8bd7-7f29baf44a88.png)

**Comment by hooh-hooah** [comment]
It seems like Reflection Probe is too small.
Related #20 

Adjust it in the menu.
