### ISSUE TITLE
head texture lighting flicker

### ISSUE THREAD

**Issue by Chernobog95** [ore-/AI_Graphics#76]
Video:
https://mega.nz/file/qD4iHIzK#vPLIIebCazbrhtogcX7q7WQFs5Pbpsuzqz7AWGRHd_s

Preset:
https://mega.nz/file/OPgQmKaa#U6i2y4gbVIwowsQ1zt8BiKNaVKYAd79AJ4xqej7ThR0

**Comment by hooh-hooah** [comment]
It seems like reflection probe problem.
Adjust Reflection Probe's Size.
Related #20

**Comment by Chernobog95** [comment]
I tried everything I could. No matter the size, with or without HDR it continues to flicker.

Video, I find this funny.
https://mega.nz/file/zPhyWAoS#91nKFZSJ7hxPqKrGN3kKjRiSDTV7uxUBiBwbrNmD7Io

Anyway the solution is to simply set intensity value to absolute 0.

**Comment by Chernobog95** [comment]
So... How do I change the button to activate AIG or VNGE? Where is the file and name of the file where shortcuts are contained.

**Comment by ore-** [comment]
op has workaround
