### ISSUE TITLE
Reflection probe control panel is disabled with trilight and flat environment

### ISSUE THREAD

**Issue by nyaacho** [ore-/AI_Graphics#86]
## Expected Behavior
Reflection probe should keep working with different clear flag, even without skybox

## Current Behavior
Reflection probe control panel is disabled with trilight and flat environment

## Used AI_Graphics Version
0.2.0

## Steps to Reproduce
1. Choose trilight or flat in Environment lighting

**Comment by ore-** [comment]
allowed this in #87
