### ISSUE TITLE
Preset Save File Versioning

### ISSUE THREAD

**Issue by hooh-hooah** [ore-/AI_Graphics#9]
**Mid-Term Goal**

When we going to change the strcture/something a bit, the save file structure changes. Also does scene embedded savings. 
We need some sort of preset structure versioning to ensure stability of the plugin.

Added from #7

**Comment by ore-** [comment]
Per [MessagePack doc](https://github.com/neuecc/MessagePack-CSharp/blob/master/README.md):

> When classes change or are extended, be careful about versioning. MessagePackSerializer will initialize members to their default value if a key does not exist in the serialized binary blob, meaning members using reference types can be initialized to null. If you use indexed (int) keys, the keys should start at 0 and should be sequential. If a later version stops using certain members, you should keep the obsolete members (C# provides an Obsolete attribute to annotate such members) until all other clients had a chance to update and remove their uses of these members as well. Also, when the values of indexed keys "jump" a lot, leaving gaps in the sequence, it will negatively affect the binary size, as null placeholders will be inserted into the resulting arrays. However, you shouldn't reuse indexes of removed members to avoid compatibility issues between clients or when trying to deserialize legacy blobs.

Just need to ensure we don't change order of serialized fields. Let me know if I'm oversimplifying this.

**Comment by hooh-hooah** [comment]
Closed for now
