### ISSUE TITLE
Some lights don't load/show in a scene after 0.3 update. 

### ISSUE THREAD

**Issue by giangole** [ore-/AI_Graphics#96]
The amounts of lights in a scene is different if I load it with 0.2 compared to 0.3.

## Expected Behavior

the lights in the scene should be the same after the update as I did not change it.
## Current Behavior

Some lights don't show up in the scene if the 0.3 of the plugin is running, the lights literally don't enlighten the map and don't show in the list of light sources.
If I revert back to 0.2 I see them

## Used AI_Graphics Version

0.3
## Steps to Reproduce

 I gave the assets (scene and item) to ore and he reproduced the issue.

**Comment by ore-** [comment]
fixed in #109
