### ISSUE TITLE
Unreliable presets in game

### ISSUE THREAD

**Issue by Chernobog95** [ore-/AI_Graphics#99]
Select 1 preset and then select another after that one then go back. The second preset won't output the same image as if you selected it the first time and the first selected preset won't look the same when selected again.

Solution? Maybe a reset button, like when you have AIGraphics enabled, enter character maker and then it activates/loads without any preset since you have to select own preset as it doesn't automatically load the last preset used nor there option for it to be default preset.

**Comment by hooh-hooah** [comment]
I cannot replicate this issue.
I need the preset that you used and reference pictures so i can pinpoint the issue. It's the tedious but it's really important to save many hours.

**Comment by ore-** [comment]
no repro from op.
